baseurl: /nl-zpp/

title: Kompilator Nianio
tagline: Optymalizacja programów Nianio kompilowanych do C
repository_url: https://github.com/jbujak/nl-zpp/

paginate: 5
paginate_path: "/nl-zpp/page/:num/"

gems:
  - jekyll-paginate

markdown: kramdown
